POST http://127.0.0.1:3000/api/data
Content-Type: application/json

{"line": "ligneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee n"}

##############################################################

GET  http://localhost:3000/api/data

##############################################################

POST http://127.0.0.1:3000/form
Content-Type: application/json

{
    "title": "test",
    "content": "Ceci est un test",
    "status": "BROUILLON",
    "author": "Jean",
}